services:
  database:
    image: 'postgis/postgis:16-3.4'
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_USER=${DBUSERNAME}
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DBUSERNAME} -d ${DBNAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: ${DBURL}
      SPRING_DATASOURCE_USERNAME: ${DBUSERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DBPASSWORD}
      UPLOADS_DIRECTORY: ${UPLOADS_DIRECTORY}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
