services:
  database:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=${DBNAME}'
      - 'POSTGRES_PASSWORD=${DBPASSWORD}'
      - 'POSTGRES_USER={DBUSERNAME}'
    ports:
      - '5432'
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: ${DBURL}
      SPRING_DATASOURCE_USERNAME: ${DBUSERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DBPASSWORD}
    depends_on:
      - database
